### ISSUE TITLE
Feature request: reload all data

### ISSUE THREAD

**Issue by gerchicov-bp** [rechsteiner/Parchment#142]
Currently you have only methods "reload around element". What if I need to change the source items and reload all the data (because I don't know how the items were changed)?

**Comment by rechsteiner** [comment]
Hi! This is needed since Parchment supports infinitely large data sources, so we need to give it the initial item to reload the data around. If not, it doesn't know where to start. The element you pass in doesn't have to be in the menu from before, so you can for instance pass in the middle element of your updated data.

I guess we could add another `reloadData()` method that only works when using a fixed number of views, as we can then reload the data based on the currently visible indexes. I'll see if I can add that in the next release!

**Comment by Gargo** [comment]
@rechsteiner hello
for example default `UITableView` has "visible elements" and reloads them only on `reloadData`.
Another strange thing is in most cases user needs to reload items around current active page. So specifying of an index may be extra

**Comment by LinusGeffarth** [comment]
Hey there. Thanks for your awesome repo! Chipping in to second this request. I'd really appreciate if you could add this feature.
Please, please do! 🙏

**Comment by rechsteiner** [comment]
Hi! I will look into adding it this weekend ✌️

**Comment by igorkaryi** [comment]
will it be possible to update all the data? not only in a certain index?

**Comment by LinusGeffarth** [comment]
To be more specific on what I'd love to see:
My app features different types of accounts, for which different navigation items are being shown. Since the user can change their account type at runtime, I need to update the navigation bar respectively: add / remove view controllers and items.
Thanks!

**Comment by igorkaryi** [comment]
my number of indices can vary. And the application crashes after the reload

**Comment by rechsteiner** [comment]
@LinusGeffarth I don't think it should be any problems adding support for that. I guess it would be nice to add support for animations when reloading the data as well. Just curious; have you tried using the current `reloadData(around:)` method or it that not working for you? You should be able to pass in the first item in the updated data and reload the data.

**Comment by LinusGeffarth** [comment]
Yes, I have. It doesn't seem to do anything, though. I also checked with breakpoints to see whether the data source methods are being called: they're not...

**Comment by rechsteiner** [comment]
@igorkaryi that's not good! Do you have any more details on the crash? I will try to get a fix out as soon as possible 🙂

**Comment by rechsteiner** [comment]
Hmm, okay. I'll look into why that's not working 😕

**Comment by igorkaryi** [comment]
it turned out to reload the data. each time to create a PageViewController

**Comment by LinusGeffarth** [comment]
Well that's more like a bad workaround rather than a solution. You would experience very bad memory issues, I'm guessing.

**Comment by igorkaryi** [comment]
then how to update list items correctly?

**Comment by LinusGeffarth** [comment]
Update from my side: after updating to 1.0.3, reloading the data using your provided method works and re-calls the data source & delegate methods.

**Comment by LinusGeffarth** [comment]
I'm also doing it the way you said, because right now, we can't do it any other way.

**Comment by LinusGeffarth** [comment]
# UPDATE

I figured out how to reload the items & view controllers properly.  

### Presets
- you're using `PagingViewController<PagingIndexItem>()` (I'm not sure it works for FixedPagingViewController)
- you need to inherit from the `PagingViewControllerDataSource`
- make your items and view controllers, that you're passing in `viewControllerForIndex` and `pagingItemForIndex` computed variables
   - since they're computed, they will change **before** reloading, this is crucial
   - alternatively, you could set them manually before reloading, that should work too

### The Magic
- at the point you want to reload your data, put **`pagingViewController.dataSource = self`** (yes, again, even if you have before, because:)
   * I figured, `pagingViewController`'s `dataSource` property has a `didSet` that calls a library-private function called `configureDataSource()` in ´PagingViewController.swift´
   * this function calls the data source methods and thereby reloads your content

**Comment by igorkaryi** [comment]
@LinusGeffarth Thank you very much

**Comment by rechsteiner** [comment]
Just released a new version of Parchment that fixes the issue with reloading data, and also introduces a new method that doesn't require you to pass in the initial item. Now you can just do this to reload data:

```Swift
pagingViewController.reloadData()
```

Please let me know if you're still seeing any issues. And thanks for the help everyone 🙏

**Comment by LinusGeffarth** [comment]
Hmm not really working well for me:

1) crashing when on an item / view controller that's gone after reloading (as described <a href="#caveat">here</a>)
2) reloading with a delay of around >1s (compared to my implementation)
3) not reloading the items all the time for me, so that it then crashes if items were removed
   - when switching between items, it does eventually reload
4) sometimes adding the new items before removing the old ones, so that for a split second there's twice the amount of items

**Comment by igorkaryi** [comment]
@rechsteiner thanks a lot, it works!!!!!)))))

**Comment by rechsteiner** [comment]
@LinusGeffarth

> 1. crashing when on an item / view controller that's gone after reloading (as described here)

I'm not able to reproduce this crash – it seems to work fine to reload data when removing items for me. Could you provide some more details on how to reproduce this?

> 2. reloading with a delay of around >1s (compared to my implementation)

Not sure I understand what you mean by this. Are you seeing a delay of around 1s when calling `reloadData`?

> 3. not reloading the items all the time for me, so that it then crashes if items were removed

Is this the same type of crash as the first point or is this related to something else? Would be great if you could provide some ways of reproducing this as well.

> 4. sometimes adding the new items before removing the old ones, so that for a split second there's twice the amount of items

Also not sure what is causing this. Are you sure this is a bug with `reloadData` and not just related to your implementation?

Would be great if you could specify a bit more on these things and I will look into getting that fixed as soon as possible. Thanks!

**Comment by LinusGeffarth** [comment]
1. I'm not able to reproduce this anymore, possibly a `command`+`shift`+`k` did the job...
2. currently, it only reloads after switching to a different paging item / view controller
    1. trigger reload
    2. tap an item that won't be there after reload (reload has not yet visually updated the items)
    3. now the menu updates, leading to the item and vc missing, leading to a crash
3. see 2
4. I don't think it is about my implementation, because, my items array is a computed variable that's already updated far before the reload...

I think the problem lies in the paging view controller not updating the menu items until the user switches to another view controller.

For now, I have switched back to 1.0.3, because my above solution works *really* reliable and fast.

I hope, this helps somehow...

**Comment by igorkaryi** [comment]
can be this. when I do an update  - pagingViewController.reloadData(), the index becomes 0

**Comment by rechsteiner** [comment]
Hmm, it seems to update instantly here 😕 Do you have any other steps that could help reproduce this?

**Comment by LinusGeffarth** [comment]
Not quite, I don't know what could be different...  
I'm assuming - even though I don't believe that - it is related to my project only. Since my custom solution works just fine for me, I'm ok with this. You shouldn't bother anymore.  
Thanks so much!

**Comment by rechsteiner** [comment]
Okay, let me know if you figure out how to reproduce it. Would love to get it fixed if there is a bug with my implementation. Thanks a lot for helping debugging this 🙌

**Comment by igorkaryi** [comment]
Yes. after reload,  return only one item

**Comment by rechsteiner** [comment]
That seems to work just fine here. In the `DelegateExample` target I'm triggering this:

```Swift
cities = ["Berlin"]
pagingViewController.reloadData()
```

Is that what you mean by returning only one item?

**Comment by rechsteiner** [comment]
Thanks!! Managed to reproduce it now. Will try to get a fix out shortly!

**Comment by rechsteiner** [comment]
Just added what (hopefully) should fix this: #157. @LinusGeffarth @igorkaryi could you target the `master` branch and see it's working for you now? 🙏

**Comment by igorkaryi** [comment]
maybe I'm doing something wrong. But I still have after the update - one menu item((((

**Comment by igorkaryi** [comment]
I'm sorry, it's my problem. API does not work from time to time

**Comment by LinusGeffarth** [comment]
Still doesn't work for me, unfortunately...

**Comment by rechsteiner** [comment]
@igorkaryi @LinusGeffarth I just merged another fix for this #201. Can you target the master branch and see if it works for you now? 🙏 Sorry about all these issues!

**Comment by LinusGeffarth** [comment]
Yasss awesome, now it works, thanks so much!!!
