### ISSUE TITLE
Please update pod and carthage to support swift 5

### ISSUE THREAD

**Issue by targen1991** [rechsteiner/Parchment#327]
Getting error after i have updated my xcode to 10.2 ,swift 5
Error : Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0 compiler: /Projects/Discovrus/APP/Discovrus/Carthage/Build/iOS/Parchment.framework/Modules/Parchment.swiftmodule/arm64.swiftmodule

<img width="1040" alt="Screenshot 2019-04-17 at 10 50 00 AM" src="https://user-images.githubusercontent.com/4649650/56262990-c552ac00-60fe-11e9-8cea-6f6d81378b3d.png">

**Comment by ikesyo** [comment]
That means that you just need to rebuild the framework with Xcode 10.2: `carthage build --platform ios`

**Comment by targen1991** [comment]
Issue has been resolved.
Thanks @ikesyo 👍

**Comment by pbyorke** [comment]
sorry, this is still an issue for us. I have uninstalled and reinstalled both Xcode and Carthage and I am still getting:
**error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'MobileFreddy')**
when I run Carthage build --platform iOS
