### ISSUE TITLE
Initial index not working with select(index: Int)

### ISSUE THREAD

**Issue by rocxteady** [rechsteiner/Parchment#435]
Hello,

After migration to 2.0.1 I realized that starting paging view controller with initial index not working.
Please see the code: https://gist.github.com/rocxteady/a731d40a939e9f8a295326ef12d50984

Thank you.

**Comment by rocxteady** [comment]
This is the commit that made the problem occurred: https://github.com/rechsteiner/Parchment/commit/15a8ba95ff70bc86a81ffa4f872101aa38266e79

But I don't know what caused it exactly.

**Comment by esatgozcu** [comment]
Same problem. We are waiting for the situation to be corrected

**Comment by rechsteiner** [comment]
Thanks for the report! I’ll try to get this fixed later today

**Comment by rechsteiner** [comment]
This should be fixed now. I need to do a bit more testing before creating a new release, so you need to target the `master` for now. Let me know if you find any issues!

**Comment by rocxteady** [comment]
Thank you @rechsteiner 🙏

**Comment by Haeuncs** [comment]
I just tested it with the latest master and it still doesn't seem to work.
pagingViewController.select(index: 3) -> go to index 4
But in viewDidAppear it works fine.
